spring.application.name=pulsepass

spring.datasource.url=${PULSEPASS_DB_URL:jdbc:postgresql://localhost:5432/pulsepass}
spring.datasource.username=${PULSEPASS_DB_USER:pulsepass}
spring.datasource.password=${PULSEPASS_DB_PASSWORD:pulsepass}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
